name = "LGV SMP 4"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab83bc338c2f25ac346d1c0c98d893247bbbae5e0a1d548f2d5243070218c1a"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
