name = "LGV SMP 4"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57123f121b42a2a7aa772b016eff5a39da5fec6bad9c8bcc9cd6efde1fbe7929"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
